#! /bin/sh
set -e

case "$1" in 
    remove|upgrade|deconfigure)
        echo "Eliminando symlink de gnome-keyring"
        rm -f /usr/lib/libgnome-keyring.so.0 2>/dev/null >/dev/null || true
    ;;

    failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument \`$1" >&2
        exit 1
    ;;
esac
 
#DEBHELPER#

exit 0
